name: ci
on:
  push:
    branches:
      - main
      - release
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # 원하는 버전으로 플러터를 설치한다.
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
      - run: flutter --version
      - name: "Run flutter pub get"
        working-directory: . # example 폴더에서 작업한다.
        run: flutter pub get
      - name: Enable flutter web
        working-directory: .
        run: flutter config --enable-web
      - name: "Build Web App"
        working-directory: .
        run: flutter build web --wasm --base-href "/primary_web/"

      # 깃 허브 배포. gh-page 브랜치에 배포를 한다. Deploy 는 working directory 필요 없음
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Github Page 에 배포하기 위한 키
          github_token: ${{ secrets.REPO_SCOPE_DEPLOY_TOKEN }}
          publish_dir: ./build/web
